### ISSUE TITLE
how to use tcp or etcd svr to read ,to replace "reader := bufio.NewReader(os.Stdin)" in example

### ISSUE THREAD

**Issue by jerriezhou** [lni/dragonboat-example#11]
how to use tcp or etcd svr to read ,to replace "reader := bufio.NewReader(os.Stdin)" in example . or are  there other client example to send Propose to example server ,thanks

**Comment by lni** [comment]
It is up to users how to get the data they want to propose. That might came from a file, a database, a remote server or some local business logic. 

Closing as this is not dragonboat specific.
