### ISSUE TITLE
ondisk restore from snapshort panic

### ISSUE THREAD

**Issue by ysbarney** [lni/dragonboat-example#13]
goroutine 186 [running]:
encoding/binary.littleEndian.Uint64(...)
	/data/open_source/go/src/encoding/binary/binary.go:77
main.(*DiskKV).queryAppliedIndex(0xc0004d9920, 0xc000306400, 0x0, 0x0, 0x0)
	/data/go_workspace/src/github.com/lni/dragonboat-example/ondisk/diskkv.go:308 +0x398
main.(*DiskKV).Open(0xc0004d9920, 0xc0005b6000, 0x0, 0x0, 0xc0007a2900)
	/data/go_workspace/src/github.com/lni/dragonboat-example/ondisk/diskkv.go:347 +0x19d
github.com/lni/dragonboat/v3/internal/rsm.(*OnDiskStateMachine).Open(0xc00011e700, 0xc0005b6000, 0xc00011e700, 0xf25ca0, 0x1635ba0)
	/data/go_workspace/pkg/mod/github.com/lni/dragonboat/v3@v3.3.0/internal/rsm/adapter.go:285 +0x4b
github.com/lni/dragonboat/v3/internal/rsm.(*NativeSM).Open(0xc0001ea0d0, 0x7f5b9a577e98, 0xc0001e2800, 0xc0007a2970)
	/data/go_workspace/pkg/mod/github.com/lni/dragonboat/v3@v3.3.0/internal/rsm/managed.go:131 +0x42
github.com/lni/dragonboat/v3/internal/rsm.(*StateMachine).OpenOnDiskStateMachine(0xc00007e000, 0x0, 0x0, 0x0)
	/data/go_workspace/pkg/mod/github.com/lni/dragonboat/v3@v3.3.0/internal/rsm/statemachine.go:413 +0xc2
github.com/lni/dragonboat/v3.(*node).recover(0xc0002d8000, 0x0, 0x0, 0x0, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/data/go_workspace/pkg/mod/github.com/lni/dragonboat/v3@v3.3.0/node.go:784 +0xf2a
github.com/lni/dragonboat/v3.(*ssWorker).recover(0xc00000eaa0, 0x0, 0x0, 0x0, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/data/go_workspace/pkg/mod/github.com/lni/dragonboat/v3@v3.3.0/engine.go:288 +0x78
github.com/lni/dragonboat/v3.(*ssWorker).handle(0xc00000eaa0, 0x0, 0x0, 0x0, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/data/go_workspace/pkg/mod/github.com/lni/dragonboat/v3@v3.3.0/engine.go:277 +0x138
github.com/lni/dragonboat/v3.(*ssWorker).workerMain(0xc00000eaa0)
	/data/go_workspace/pkg/mod/github.com/lni/dragonboat/v3@v3.3.0/engine.go:265 +0x78
github.com/lni/dragonboat/v3.newSSWorker.func1()
	/data/go_workspace/pkg/mod/github.com/lni/dragonboat/v3@v3.3.0/engine.go:251 +0x2a
github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1(0xc00000e9e0, 0xc0003104b0, 0x0, 0x0, 0xc0001e3400)
	/data/go_workspace/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:79 +0x3a
created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
	/data/go_workspace/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:74 +0x98

There is some problem in here
func (d *DiskKV) Update(ents []sm.Entry) ([]sm.Entry, error) {
...
idx := fmt.Sprintf("%d", ents[len(ents)-1].Index)
wb.Set([]byte(appliedIndexKey), []byte(idx), db.wo)
...
}

change to these 
func (d *DiskKV) Update(ents []sm.Entry) ([]sm.Entry, error) {
...
bidx := make([]byte, 8)
binary.LittleEndian.PutUint64(bidx, ents[len(ents)-1].Index)
wb.Set([]byte(appliedIndexKey), bidx, db.wo)
...
}

**Comment by lni** [comment]
Thanks for reporting the bug. That issue was caused by a bad merge and it has now been fixed.
