### ISSUE TITLE
ondisk example is unable to recover from crash

### ISSUE THREAD

**Issue by intrntbrn** [lni/dragonboat-example#14]
When trying to restart a failed node, a goroutine panics. 

I guess it's best to demonstrate the issue with a simple gif:

![dragonboat_clean](https://user-images.githubusercontent.com/1234183/109673021-e5b27500-7b75-11eb-92ea-f19ba40589ce.gif)

I just killed node 3 by pressing ctrl-c, and tried to relaunch it with `./example-ondisk -nodeid 3` and `./example-ondisk -nodeid 3 -join`.

**Comment by lni** [comment]
dup of #13 

thanks for reporting, fixed.
