### ISSUE TITLE
Cannot resolve reference to regular client session example

### ISSUE THREAD

**Issue by marcus-orchard** [lni/dragonboat-example#15]
I've gone through this and so far so good.

However, there is a reference to an example using something other than the no-op client session, but I can't seem to find it:

[Example code line](https://github.com/lni/dragonboat-example/blob/79f3d372190ee23705517f193dfe7cc839b34a14/helloworld/main.go#L285)

Apologies in advance if I'm completely missing it. Honest, I've looked.

**Comment by lni** [comment]
The examples shipped with the v3.2.x releases can be found in the link below
https://github.com/lni/dragonboat/blob/release-3.2/example_test.go

They were removed from the v3.3.x release for various reasons.
