### ISSUE TITLE
Why update function need return sm.Result ?

### ISSUE THREAD

**Issue by BAN1ce** [lni/dragonboat-example#17]
Hi, Why update function need return sm.Result . what is the purpose for this design ?  Is sm.Result will use in my own program logic ?  I am confuse about the Result.Value and Result.Data .

In helloworld example sm.Result.Value = uint64(len(data)) , Why this value is  uint64(len(data)) ? 

```

func (s *ExampleStateMachine) Update(data []byte) (sm.Result, error) {
	// in this example, we print out the following hello world message for each
	// incoming update request. we also increase the counter by one to remember
	// how many updates we have applied
	s.Count++
	fmt.Printf("from ExampleStateMachine.Update(), msg: %s, count:%d\n",
		string(data), s.Count)
	return sm.Result{Value: uint64(len(data))}, nil
}

```

**Comment by lni** [comment]
It returns a sm.Result so the client that made the proposal can know what is the execution outcome of its proposal. 

Your program is free to return whatever result necessary. The above example returns uint64(len(data)) just as an example. 

Result.Value is just a value, it provides an easy way to return a single value without any allocation. If such a single value is not enough, you can then use the Result.Data field to return a []byte, by doing that your program is in charge of the allocation.
