### ISSUE TITLE
regarding multiple raft group

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat-example#24]
@lni 
regarding multiple raft group
what does it mean?

i've seen the code but it seems there are two groups that use the same localhost ports.

i understand how raft works but when it comes to updates, how does it work when consistencies between two groups work?

for multiple raft group example, why do u make it into 1 server instead of 2? can u do that in 2 server example? because i expect each raft group to at least be in their own server instance for testing purposes.

**Comment by lni** [comment]
Please read the paper and the code to get some basic understanding on raft & distributed system first.
