### ISSUE TITLE
RUN  helloworld example  error!

### ISSUE THREAD

**Issue by forging2012** [lni/dragonboat-example#6]
# github.com/lni/dragonboat/internal/logdb/gorocksdb
../github.com/lni/dragonboat/internal/logdb/gorocksdb/backup.go:5:10: fatal error: 'rocksdb/c.h' file not found
#include "rocksdb/c.h"
         ^~~~~~~~~~~~~
1 error generated.

**Comment by lni** [comment]
already addressed in https://github.com/lni/dragonboat/pull/27
