### ISSUE TITLE
C++ examples

### ISSUE THREAD

**Issue by JasonYuchen** [lni/dragonboat-example#8]
I re-implemented some C++ examples according to the Go examples. Those who are interested in C++ binding can refer to [these examples](https://github.com/JasonYuchen/dragonboat-cpp-example)

**Comment by lni** [comment]
Thanks for the examples. I've linked them in the README pages. 

https://github.com/lni/dragonboat-example/tree/on-disk-state-machine

It will be merged to master once dragonboat v3.0 is released.
